# This file configures the Dart analyzer for your Flutter project.
# It enforces rules, catches errors early, and can apply fixes automatically.

# ✅ Use Flutter's recommended lint rules as a base
analyzer:
  errors:
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🔹 Automatically prefer const where possible
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables

    # 🔹 Some extra recommended rules (optional but helpful)
    - always_declare_return_types
    - avoid_print
    - prefer_final_fields
    - unnecessary_this
    - use_key_in_widget_constructors

# 🔹 Run `dart fix --apply` to bulk apply fixes once
# 🔹 With VS Code, also add the following to .vscode/settings.json to fix on save:
#
# {
#   "editor.formatOnSave": true,
#   "editor.codeActionsOnSave": {
#     "source.fixAll": true
#   }
# }
