// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlrvkNrL5CmcowATXwTSO9j6RuSH74Js',
    appId: '1:665487166785:web:a0c62540cf707de2cce5c0',
    messagingSenderId: '665487166785',
    projectId: 'chat-app-4feba',
    authDomain: 'chat-app-4feba.firebaseapp.com',
    storageBucket: 'chat-app-4feba.firebasestorage.app',
    measurementId: 'G-BYWGX46MY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJAXRUV8wgD5QZbeUaYkka30eamkkWoY',
    appId: '1:665487166785:android:8d0cfbe3779ceca4cce5c0',
    messagingSenderId: '665487166785',
    projectId: 'chat-app-4feba',
    storageBucket: 'chat-app-4feba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkCoAGoPi_MAtCLDfZDaDHkzSts-9YxEQ',
    appId: '1:665487166785:ios:14f1463e5133613fcce5c0',
    messagingSenderId: '665487166785',
    projectId: 'chat-app-4feba',
    storageBucket: 'chat-app-4feba.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkCoAGoPi_MAtCLDfZDaDHkzSts-9YxEQ',
    appId: '1:665487166785:ios:14f1463e5133613fcce5c0',
    messagingSenderId: '665487166785',
    projectId: 'chat-app-4feba',
    storageBucket: 'chat-app-4feba.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlrvkNrL5CmcowATXwTSO9j6RuSH74Js',
    appId: '1:665487166785:web:6527fec847c17ceccce5c0',
    messagingSenderId: '665487166785',
    projectId: 'chat-app-4feba',
    authDomain: 'chat-app-4feba.firebaseapp.com',
    storageBucket: 'chat-app-4feba.firebasestorage.app',
    measurementId: 'G-6X6XHS8L4K',
  );
}
